os: linux

stages:
  - compile

jobs:
  include:
    - stage: compile
      name: "Build and test Backend"
      language: java
      java: 11
      before_script:
        - cd fisa-backend
      script:
        - mvn checkstyle:check
        - mvn compile
        - mvn test
    - stage: compile
      name: "Build and test Frontend"
      language: node_js
      node_js: 14
      before_script:
        - cd fisa-frontend
      script:
        - npm i
        - npm run lint
        - npm run build
        - npm t

services:
- docker
