os: linux

stages:
  - compile
  - deploy

jobs:
  include:
    - stage: compile
      name: "Build and test Backend"
      language: java
      java: 11
      before_script:
        - cd fisa-backend
      script:
        - mvn checkstyle:check
        - mvn compile
        - mvn test
    - stage: compile
      name: "Build and test Frontend"
      language: node_js
      node_js: 14
      before_script:
        - cd fisa-frontend
      script:
        - npm i
        - npm run lint
        - npm run build
        - npm t
    - stage: deploy
      name: "Build and upload image for Backend"
      before_script:
        - cd fisa-backend
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then exit; fi'
        - docker build -t fisa:backend .
        - docker login -u "$user" -p "$token" https://docker.pkg.github.com
        - docker push fisa:backend

services:
- docker
