version: "3.4"

services:
  fisa-frontend:
    image: gitlab-ext.iosb.fraunhofer.de:4567/ilt-pse/pse2020/fisa-implementierung:frontend
    ports:
      - "3000:80"
    environment:
      - API_URL=http://localhost:8081
  fisa-backend:
    image: gitlab-ext.iosb.fraunhofer.de:4567/ilt-pse/pse2020/fisa-implementierung:backend
    ports:
      - "8081:8081"
    environment:
      - app.filesDirectory=fisa
    volumes:
      - fisa-backend_volume:/fisa

volumes:
  fisa-backend_volume:
