version: "3.4"

services:
  fisa-frontend:
    image: maxomagier/fisa-test:frontend
    ports:
      - "3000:80"
    environment:
      - API_URL=http://localhost:8081
  fisa-backend:
    image: maxomagier/fisa-test:backend
    ports:
      - "8081:8081"
    environment:
      - app.filesDirectory=fisa
    volumes:
      - fisa-backend_volume:/fisa

volumes:
  fisa-backend_volume:
