import { FisaObjectDefinitionI } from '../../../redux/interfaces';

export const objectDefinitionsWithoutRoot: () => FisaObjectDefinitionI[] = () => [
  {
    name: 'Raum',
    caption: 'Räume',
    infoText: 'Ein Raum in dem sich Sensoren befinden.',
    mapsTo: 'STA.Thing',
    isTopLayer: true,
    isNotReusable: undefined,
    exampleData: undefined,
    positionAttributes: undefined,
    attributes: [
      {
        name: 'Name',
        valueType: 'string',
        infoText: 'Der Name des Raums',
        validationRule: '([A-Z][a-z])+',
        mapsTo: 'STA.Thing.name',
        value: undefined,
        isPredefined: undefined,
        dropDownValues: undefined,
      },
      {
        name: 'Beschreibung',
        infoText: 'Weitere Informationen',
        valueType: 'string',
        mapsTo: 'STA.Thing.description',
        value: undefined,
        isPredefined: undefined,
        dropDownValues: undefined,
        validationRule: undefined,
      },
    ],
    children: [
      {
        objectName: 'Ort',
        quantity: 1,
      },
      {
        objectName: 'Datenstrom',
        quantity: -1,
      },
    ],
  },
  {
    name: 'Datenstrom',
    caption: 'Datenströme',
    mapsTo: 'STA.Datastream',
    isTopLayer: undefined,
    exampleData: undefined,
    isNotReusable: true,
    infoText: undefined,
    positionAttributes: undefined,
    attributes: [
      {
        name: 'Name',
        valueType: 'string',
        infoText: 'Der Name des Datenstroms',
        validationRule: '([A-Z][a-z])+',
        mapsTo: 'STA.Datastream.name',
        isPredefined: undefined,
        dropDownValues: undefined,
        value: undefined,
      },
      {
        name: 'Beschreibung',
        valueType: 'string',
        mapsTo: 'STA.Datastream.description',
        isPredefined: undefined,
        dropDownValues: undefined,
        value: undefined,
        infoText: undefined,
        validationRule: undefined,
      },
      {
        name: 'Beobachtungstyp',
        valueType: 'string',
        mapsTo: 'STA.Datastream.observationType',
        isPredefined: undefined,
        dropDownValues: undefined,
        value: undefined,
        infoText: undefined,
        validationRule: undefined,
      },
    ],
    children: [
      {
        objectName: 'Sensor',
        quantity: 1,
      },
      {
        objectName: 'Sensortyp',
        quantity: -1,
      },
    ],
  },
  {
    name: 'Sensor',
    caption: 'Sensoren',
    mapsTo: 'STA.Sensor',
    isTopLayer: undefined,
    exampleData: undefined,
    isNotReusable: undefined,
    infoText: undefined,
    positionAttributes: undefined,
    attributes: [
      {
        name: 'Name',
        valueType: 'string',
        infoText: 'Der Name des Sensors',
        mapsTo: 'STA.Sensor.name',
        isPredefined: undefined,
        dropDownValues: undefined,
        value: undefined,
        validationRule: undefined,
      },
      {
        name: 'Beschreibung',
        infoText: 'Weitere Informationen',
        valueType: 'string',
        mapsTo: 'STA.Sensor.description',
        isPredefined: undefined,
        dropDownValues: undefined,
        value: undefined,
        validationRule: undefined,
      },
      {
        name: 'Codierungstyp',
        valueType: 'string',
        value: 'application/pdf',
        isPredefined: true,
        mapsTo: 'STA.Sensor.encodingType',
        dropDownValues: undefined,
        infoText: undefined,
        validationRule: undefined,
      },
      {
        name: 'Metadaten',
        valueType: 'string',
        mapsTo: 'STA.Sensor.metadata',
        isPredefined: undefined,
        dropDownValues: undefined,
        value: undefined,
        infoText: undefined,
        validationRule: undefined,
      },
    ],
    children: [],
  },
  {
    name: 'Sensortyp',
    caption: 'Sensortypen',
    mapsTo: 'STA.ObservedProperty',
    infoText: undefined,
    isNotReusable: undefined,
    isTopLayer: undefined,
    exampleData: undefined,
    positionAttributes: undefined,
    attributes: [
      {
        name: 'Name',
        valueType: 'string',
        infoText: 'Die Spezifizierung des Sensortyps',
        mapsTo: 'STA.ObservedProperty.name',
        isPredefined: undefined,
        dropDownValues: undefined,
        value: undefined,
        validationRule: undefined,
      },
      {
        name: 'Beschreibung',
        valueType: 'string',
        mapsTo: 'STA.ObservedProperty.description',
        isPredefined: undefined,
        dropDownValues: undefined,
        value: undefined,
        infoText: undefined,
        validationRule: undefined,
      },
      {
        name: 'Definition',
        valueType: 'string',
        mapsTo: 'STA.ObservedProperty.definition',
        isPredefined: undefined,
        dropDownValues: undefined,
        value: undefined,
        infoText: undefined,
        validationRule: undefined,
      },
    ],
    children: [],
  },
  {
    name: 'Ort',
    caption: 'Orte',
    mapsTo: 'STA.Location',
    isTopLayer: undefined,
    exampleData: undefined,
    isNotReusable: undefined,
    infoText: undefined,
    positionAttributes: ['Breitengrad', 'Längengrad'],
    attributes: [
      {
        name: 'Name',
        valueType: 'string',
        infoText: 'Name der Position',
        mapsTo: 'STA.Location.name',
        isPredefined: undefined,
        dropDownValues: undefined,
        value: undefined,
        validationRule: undefined,
      },
      {
        name: 'Beschreibung',
        valueType: 'string',
        mapsTo: 'STA.Location.description',
        isPredefined: undefined,
        dropDownValues: undefined,
        value: undefined,
        infoText: undefined,
        validationRule: undefined,
      },
      {
        name: 'Codierungstyp',
        valueType: 'string',
        value: 'point',
        isPredefined: true,
        mapsTo: 'STA.Location.encodingType',
        dropDownValues: undefined,
        infoText: undefined,
        validationRule: undefined,
      },
      {
        name: 'Typ',
        valueType: 'string',
        value: 'Point',
        isPredefined: true,
        mapsTo: 'STA.Location.location[type]',
        dropDownValues: undefined,
        infoText: undefined,
        validationRule: undefined,
      },
      {
        name: 'Längengrad',
        valueType: 'number',
        infoText: 'Der Längengrad des Positionspunktes',
        mapsTo: 'STA.Location.location[coordinates][0]',
        isPredefined: undefined,
        dropDownValues: undefined,
        value: undefined,
        validationRule: undefined,
      },
      {
        name: 'Breitengrad',
        valueType: 'number',
        infoText: 'Der Breitengrad des Positionpunktes',
        mapsTo: 'STA.Location.location[coordinates][1]',
        isPredefined: undefined,
        dropDownValues: undefined,
        value: undefined,
        validationRule: undefined,
      },
    ],
    children: [],
  },
];

export const objectDefinitions: () => FisaObjectDefinitionI[] = () => [
  {
    name: 'Mein Projekt',
    caption: undefined,
    isNotReusable: true,
    attributes: [],
    positionAttributes: undefined,
    children: [
      {
        objectName: 'Raum',
        quantity: 0,
      },
    ],
    infoText: undefined,
    isTopLayer: undefined,
    mapsTo: 'ErrorMapsTo',
    exampleData: undefined,
  },
  ...objectDefinitionsWithoutRoot(),
];

test('Fake Test', () => {
  expect(true).toBeTruthy();
});
